export const companyMeta = {
  name: "알터즈",
  email: "artause23@gmail.com",
  instagramMain: "https://www.instagram.com/artause_official",
  instagramSpotlight: "https://www.instagram.com/spotlight_performance",
  promoForm: "https://forms.gle/9V2cZAb37gh2sbvq7",
}

export const valueProps = [
  {
    title: "공연을 더 잘 보이게",
    description: "카드뉴스·쇼츠·관람 포인트 중심의 홍보 제작으로 공연의 매력을 빠르게 전달합니다.",
  },
  {
    title: "관객과 더 가깝게",
    description: "초대권 이벤트와 참여형 콘텐츠로 관객의 경험을 확장하고 커뮤니티를 활성화합니다.",
  },
  {
    title: "운영을 더 효율적으로",
    description: "관객 관리·전환 추적을 위한 웹서비스를 준비 중입니다. 데이터 기반 운영을 지원합니다.",
  },
]

export const shows = [
  {
    title: "은의 밤",
    status: "진행중",
    tags: ["연극", "홍보 기획"],
    description: "관람 포인트는 추후 업데이트 예정입니다.",
    ctaLabel: "예매/문의",
    ctaHref: "/contact",
    instagram: "https://www.instagram.com/spotlight_performance",
  },
  {
    title: "햄릿재판",
    status: "진행중",
    tags: ["연극", "홍보 기획"],
    description: "관람 포인트는 추후 업데이트 예정입니다.",
    ctaLabel: "예매/문의",
    ctaHref: "/contact",
    instagram: "https://www.instagram.com/spotlight_performance",
  },
  {
    title: "나의 빈틈메이트",
    status: "진행중",
    tags: ["연극", "홍보 기획"],
    description: "관람 포인트는 추후 업데이트 예정입니다.",
    ctaLabel: "예매/문의",
    ctaHref: "/contact",
    instagram: "https://www.instagram.com/spotlight_performance",
  },
  {
    title: "존재의 숨결",
    status: "준비중",
    tags: ["준비 중", "다원근", "홍보 기획"],
    description: "공개 예정. 상세 정보는 추후 업데이트됩니다.",
    ctaLabel: "알림 신청",
    ctaHref: "/contact",
    instagram: "https://www.instagram.com/artause_official",
  },
  {
    title: "세 명의 여자들",
    status: "준비중",
    tags: ["준비 중", "연극", "홍보 기획"],
    description: "공개 예정. 상세 정보는 추후 업데이트됩니다.",
    ctaLabel: "알림 신청",
    ctaHref: "/contact",
    instagram: "https://www.instagram.com/artause_official",
  },
]

export const works = [
  {
    title: "은의 밤",
    tags: ["공연 홍보 제작", "연극"],
    description: "역할: 홍보 기획 · 포인트: 공연 메시지 구조화",
  },
  {
    title: "햄릿재판",
    tags: ["공연 홍보 제작", "연극"],
    description: "역할: 홍보 기획 · 포인트: 관람 포인트 큐레이션",
  },
  {
    title: "나의 빈틈메이트",
    tags: ["공연 홍보 제작", "연극"],
    description: "역할: 홍보 기획 · 포인트: 관객 메시지 정리",
  },
]

export const services = [
  {
    title: "무료 홍보",
    description: "검토/선별 기반으로 공연의 핵심 메시지를 도출합니다.",
    items: ["대상: 초기 공연/독립 작품", "제공물: 카드뉴스/요약 콘텐츠", "흐름: 접수 → 검토 → 제작"],
  },
  {
    title: "콘텐츠 제작",
    description: "카드뉴스·쇼츠 기반으로 관람 포인트를 전달합니다.",
    items: ["대상: 홍보 강화가 필요한 공연", "제공물: 카드뉴스/쇼츠/관람 포인트", "흐름: 자료 수집 → 제작 → 확산"],
  },
  {
    title: "초대권 이벤트 운영",
    description: "참여·선정·공지 프로세스를 운영합니다.",
    items: ["대상: 관객 참여 확대 필요 공연", "제공물: 이벤트 페이지/운영/공지", "흐름: 기획 → 모집 → 선정"],
  },
]

export const contactCards = [
  {
    title: "홍보/제작 문의",
    description: "공연 홍보 콘텐츠 제작, 카드뉴스/쇼츠 제작 문의",
    ctaLabel: "메일 보내기",
    href: "mailto:artause23@gmail.com",
    variant: "secondary",
  },
  {
    title: "무료 홍보 신청",
    description: "검토 기준을 확인한 뒤 신청해 주세요.",
    ctaLabel: "신청하기",
    href: "https://forms.gle/8ErT85n5XeirqBWz9",
    variant: "primary",
  },
  {
    title: "이벤트 참여/알림",
    description: "초대권 이벤트 참여 및 알림을 받고 싶다면 연락 주세요.",
    ctaLabel: "알림 받기",
    href: "mailto:artause23@gmail.com",
    variant: "secondary",
  },
  {
    title: "기타 협업",
    description: "브랜드/기관/프로젝트 협업 제안을 기다립니다.",
    ctaLabel: "협업 제안",
    href: "mailto:artause23@gmail.com",
    variant: "ghost",
  },
]

export const portfolioItems = [
  {
    slug: "eun-ui-bam",
    id: "pfwork01-0000-4000-8000-000000000001",
    title: "은의 밤",
    category: "공연 홍보 제작",
    role: "기획/편집",
    genre: "연극",
    period: "2024.11.01 ~ 2024.12.15",
    venue: "대학로 아트원 씨어터",
    format: "카드뉴스 · 쇼츠",
    keywords: ["관람 포인트", "메시지 구조화", "SNS 확산"],
    highlight: "관람 포인트를 3개의 핵심 메시지로 재구성",
    description: "관람 포인트를 3개의 핵심 메시지로 재구성하여 관객의 이해도를 높였습니다. SNS 확산을 위한 콘텐츠 전략을 수립하고 실행했습니다.",
    challenge: "공연의 복잡한 스토리를 간결하게 전달하면서도 감정적 몰입을 유지하는 것이 과제였습니다.",
    solution: "관객 리뷰 분석을 통해 핵심 감동 포인트 3가지를 도출하고, 각 포인트를 하나의 비주얼 스토리로 구성했습니다.",
    results: ["SNS 도달률 15K+", "이벤트 참여 200+ 명", "평균 체류시간 45초 증가"],
    instagram: "https://www.instagram.com/spotlight_performance",
    poster: "/images/poster/KakaoTalk_20250618_110721711.jpg",
  },
  {
    slug: "hamlet-trial",
    id: "pfwork01-0000-4000-8000-000000000002",
    title: "햄릿재판",
    category: "공연 홍보 제작",
    role: "기획/편집",
    genre: "연극",
    period: "2025.03.01 ~ 2025.04.07",
    venue: "홍대 라이브홀",
    format: "카드뉴스 · 포인트 큐레이션",
    keywords: ["톤앤매너", "관객 메시지", "콘텐츠 리프레시"],
    highlight: "카드뉴스로 작품 톤앤매너를 선명하게 전달",
    description: "기존 홍보 콘텐츠를 분석하고 새로운 톤앤매너로 리프레시하여 관객 참여율을 크게 향상시켰습니다.",
    challenge: "이미 공연 중인 작품의 홍보 콘텐츠를 어떻게 새롭게 전달할 것인가가 핵심 과제였습니다.",
    solution: "기존 홍보와 차별화된 '법정 컨셉'을 강조하고, 배우들의 열연을 중심으로 한 비주얼 스토리텔링을 구성했습니다.",
    results: ["콘텐츠 조회수 20K+", "참여 전환율 18% 증가", "SNS 공유 300+ 회"],
    instagram: "https://www.instagram.com/spotlight_performance",
    poster: "/images/poster/2025햄재포스터_고화질.jpg",
  },
  {
    slug: "empty-mate",
    id: "pfwork01-0000-4000-8000-000000000003",
    title: "나의 빈틈메이트",
    category: "공연 홍보 제작",
    role: "기획/편집",
    genre: "연극",
    period: "2025.06.10 ~ 2025.07.20",
    venue: "대학로 씨어터 가든",
    format: "카드뉴스 · 리뷰 기반 요약",
    keywords: ["관객 후기", "핵심 포인트", "브랜드 보이스"],
    highlight: "관객 리뷰 기반 관람 포인트 정리",
    description: "실제 관객 후기를 분석하여 공연의 진정한 매력 포인트를 발굴하고, 이를 예비 관객에게 효과적으로 전달했습니다.",
    challenge: "관객들이 느끼는 감동을 어떻게 예비 관객에게 진정성 있게 전달할 것인가가 과제였습니다.",
    solution: "실제 관객 리뷰 50+ 개를 분석하여 가장 많이 언급된 감동 포인트 3가지를 시각화하고, 후기 인용을 활용한 신뢰도 높은 콘텐츠를 제작했습니다.",
    results: ["리뷰 기반 콘텐츠 참여율 25% 향상", "예매 전환율 12% 증가", "관객 후기 추가 50+ 건 확보"],
    instagram: "https://www.instagram.com/spotlight_performance",
    poster: "/images/poster/1.png",
  },
  {
    slug: "breath-of-existence",
    id: "pfwork01-0000-4000-8000-000000000004",
    title: "존재의 숨결",
    category: "공연 홍보 제작",
    role: "기획/편집",
    genre: "연극",
    period: "2026.01.15 ~ 2026.02.20",
    venue: "성수 아트홀",
    format: "카드뉴스 · 티저 콘텐츠",
    keywords: ["핵심 장면", "메시지 정리", "사전 홍보"],
    highlight: "공연 메시지를 관객 언어로 정리",
    description: "철학적이고 무거운 주제를 대중이 쉽게 이해할 수 있는 언어로 재해석하여 접근성을 높였습니다.",
    challenge: "어렵고 추상적인 주제를 어떻게 일반 관객에게 흥미롭게 전달할 것인가가 핵심 과제였습니다.",
    solution: "일상적인 질문('나는 누구인가?')으로 시작하여 공연의 철학적 주제로 자연스럽게 연결하는 스토리라인을 구성했습니다.",
    results: ["사전 예매 목표 120% 달성", "젊은 관객층 40% 증가", "SNS 반응 긍정 비율 85%"],
    instagram: "https://www.instagram.com/spotlight_performance",
    poster: "/images/poster/KakaoTalk_20260128_150000261_02.jpg",
  },
  {
    slug: "three-women",
    id: "pfwork01-0000-4000-8000-000000000005",
    title: "세 여자 이야기",
    category: "공연 홍보 제작",
    role: "기획/편집",
    genre: "연극",
    period: "2026.02.01 ~ 2026.03.10",
    venue: "대학로 예술극장",
    format: "카드뉴스 · 숏폼",
    keywords: ["장면 중심", "메시지 구성", "관객 유입"],
    highlight: "공연의 핵심 장면을 중심으로 메시지 구성",
    description: "여성 캐릭터의 강렬한 서사를 시각적으로 구현하고, 각 캐릭터의 매력을 극대화한 콘텐츠를 제작했습니다.",
    challenge: "세 명의 주인공을 균형있게 소개하면서도 각자의 개성을 살리는 것이 과제였습니다.",
    solution: "각 캐릭터를 대표하는 색상과 키워드를 설정하고, 3부작 콘텐츠로 구성하여 순차적으로 공개하는 전략을 사용했습니다.",
    results: ["여성 관객 비율 65% 달성", "시리즈 콘텐츠 완독률 78%", "공연 예매 시작 2일 만에 50% 판매"],
    instagram: "https://www.instagram.com/spotlight_performance",
    poster: "/images/poster/KakaoTalk_20260130_163437518.png",
  },
]
